In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [2]:
dataset=pd.read_csv("Teen_Mental_Health_Dataset.csv")

In [3]:
dataset

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,18,female,6.8,Instagram,6.6,2.0,2.76,1.0,low,3,4,4,0
1196,16,male,2.3,Both,8.0,1.9,2.12,0.4,high,7,4,4,0
1197,14,female,1.7,Both,8.7,0.7,3.98,0.8,high,1,1,1,0
1198,15,male,3.9,Both,8.5,2.1,3.19,0.6,high,7,9,9,0
1199,16,female,4.7,TikTok,6.5,1.0,2.91,0.9,medium,5,7,3,0

In [4]:
dataset.dropna(inplace=True)

In [5]:
dataset = pd.get_dummies(dataset, columns=["gender", "platform_usage"], drop_first=True)

In [6]:
le = LabelEncoder()

In [7]:
dataset["social_interaction_level"] = le.fit_transform(dataset["social_interaction_level"])

In [8]:
dataset

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label,gender_male,platform_usage_Instagram,platform_usage_TikTok
0,14,7.9,7.4,2.9,3.01,1.5,1,2,2,1,0,True,True,False
1,19,1.9,8.0,2.9,3.22,0.8,0,8,1,10,0,False,False,True
2,17,1.3,7.6,0.5,3.92,0.0,0,2,4,2,0,False,True,False
3,15,7.4,6.9,1.6,3.48,0.8,2,1,7,9,0,True,False,True
4,15,4.7,4.9,3.0,2.37,1.4,2,3,5,2,0,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,18,6.8,6.6,2.0,2.76,1.0,1,3,4,4,0,False,True,False
1196,16,2.3,8.0,1.9,2.12,0.4,0,7,4,4,0,True,False,False
1197,14,1.7,8.7,0.7,3.98,0.8,0,1,1,1,0,False,False,False
1198,15,3.9,8.5,2.1,3.19,0.6,0,7,9,9,0,True,False,False
1199,16,4.7,6.5,1.0,2.91,0.9,2,5,7,3,0,False,False,True

In [9]:
X = dataset.drop(columns=["social_interaction_level"])
y = dataset["social_interaction_level"]

In [10]:
dataset.to_csv("preprocessed_social_interaction.csv", index=False)

In [11]:
dataset

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label,gender_male,platform_usage_Instagram,platform_usage_TikTok
0,14,7.9,7.4,2.9,3.01,1.5,1,2,2,1,0,True,True,False
1,19,1.9,8.0,2.9,3.22,0.8,0,8,1,10,0,False,False,True
2,17,1.3,7.6,0.5,3.92,0.0,0,2,4,2,0,False,True,False
3,15,7.4,6.9,1.6,3.48,0.8,2,1,7,9,0,True,False,True
4,15,4.7,4.9,3.0,2.37,1.4,2,3,5,2,0,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,18,6.8,6.6,2.0,2.76,1.0,1,3,4,4,0,False,True,False
1196,16,2.3,8.0,1.9,2.12,0.4,0,7,4,4,0,True,False,False
1197,14,1.7,8.7,0.7,3.98,0.8,0,1,1,1,0,False,False,False
1198,15,3.9,8.5,2.1,3.19,0.6,0,7,9,9,0,True,False,False
1199,16,4.7,6.5,1.0,2.91,0.9,2,5,7,3,0,False,False,True