In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("Teen_Mental_Health_Dataset.csv")

In [3]:
dataset

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label
0,14,male,7.9,Instagram,7.4,2.9,3.01,1.5,low,2,2,1,0
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0
3,15,male,7.4,TikTok,6.9,1.6,3.48,0.8,medium,1,7,9,0
4,15,female,4.7,Both,4.9,3.0,2.37,1.4,medium,3,5,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,18,female,6.8,Instagram,6.6,2.0,2.76,1.0,low,3,4,4,0
1196,16,male,2.3,Both,8.0,1.9,2.12,0.4,high,7,4,4,0
1197,14,female,1.7,Both,8.7,0.7,3.98,0.8,high,1,1,1,0
1198,15,male,3.9,Both,8.5,2.1,3.19,0.6,high,7,9,9,0
1199,16,female,4.7,TikTok,6.5,1.0,2.91,0.9,medium,5,7,3,0

In [6]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [7]:
dataset

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,depression_label,gender_male,platform_usage_Instagram,platform_usage_TikTok,social_interaction_level_low,social_interaction_level_medium
0,14,7.9,7.4,2.9,3.01,1.5,2,2,1,0,1,1,0,1,0
1,19,1.9,8.0,2.9,3.22,0.8,8,1,10,0,0,0,1,0,0
2,17,1.3,7.6,0.5,3.92,0.0,2,4,2,0,0,1,0,0,0
3,15,7.4,6.9,1.6,3.48,0.8,1,7,9,0,1,0,1,0,1
4,15,4.7,4.9,3.0,2.37,1.4,3,5,2,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,18,6.8,6.6,2.0,2.76,1.0,3,4,4,0,0,1,0,1,0
1196,16,2.3,8.0,1.9,2.12,0.4,7,4,4,0,1,0,0,0,0
1197,14,1.7,8.7,0.7,3.98,0.8,1,1,1,0,0,0,0,0,0
1198,15,3.9,8.5,2.1,3.19,0.6,7,9,9,0,1,0,0,0,0
1199,16,4.7,6.5,1.0,2.91,0.9,5,7,3,0,0,0,1,0,1

In [8]:
dataset.isnull().sum()

age                                0
daily_social_media_hours           0
sleep_hours                        0
screen_time_before_sleep           0
academic_performance               0
physical_activity                  0
stress_level                       0
anxiety_level                      0
addiction_level                    0
depression_label                   0
gender_male                        0
platform_usage_Instagram           0
platform_usage_TikTok              0
social_interaction_level_low       0
social_interaction_level_medium    0
dtype: int64

In [9]:
dataset.dropna(inplace=True)

In [10]:
dataset

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,depression_label,gender_male,platform_usage_Instagram,platform_usage_TikTok,social_interaction_level_low,social_interaction_level_medium
0,14,7.9,7.4,2.9,3.01,1.5,2,2,1,0,1,1,0,1,0
1,19,1.9,8.0,2.9,3.22,0.8,8,1,10,0,0,0,1,0,0
2,17,1.3,7.6,0.5,3.92,0.0,2,4,2,0,0,1,0,0,0
3,15,7.4,6.9,1.6,3.48,0.8,1,7,9,0,1,0,1,0,1
4,15,4.7,4.9,3.0,2.37,1.4,3,5,2,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,18,6.8,6.6,2.0,2.76,1.0,3,4,4,0,0,1,0,1,0
1196,16,2.3,8.0,1.9,2.12,0.4,7,4,4,0,1,0,0,0,0
1197,14,1.7,8.7,0.7,3.98,0.8,1,1,1,0,0,0,0,0,0
1198,15,3.9,8.5,2.1,3.19,0.6,7,9,9,0,1,0,0,0,0
1199,16,4.7,6.5,1.0,2.91,0.9,5,7,3,0,0,0,1,0,1

In [11]:
dataset["social_interaction_level_medium"].fillna(dataset["social_interaction_level_medium"].mean(),inplace=True)

In [12]:
dataset

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,depression_label,gender_male,platform_usage_Instagram,platform_usage_TikTok,social_interaction_level_low,social_interaction_level_medium
0,14,7.9,7.4,2.9,3.01,1.5,2,2,1,0,1,1,0,1,0
1,19,1.9,8.0,2.9,3.22,0.8,8,1,10,0,0,0,1,0,0
2,17,1.3,7.6,0.5,3.92,0.0,2,4,2,0,0,1,0,0,0
3,15,7.4,6.9,1.6,3.48,0.8,1,7,9,0,1,0,1,0,1
4,15,4.7,4.9,3.0,2.37,1.4,3,5,2,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,18,6.8,6.6,2.0,2.76,1.0,3,4,4,0,0,1,0,1,0
1196,16,2.3,8.0,1.9,2.12,0.4,7,4,4,0,1,0,0,0,0
1197,14,1.7,8.7,0.7,3.98,0.8,1,1,1,0,0,0,0,0,0
1198,15,3.9,8.5,2.1,3.19,0.6,7,9,9,0,1,0,0,0,0
1199,16,4.7,6.5,1.0,2.91,0.9,5,7,3,0,0,0,1,0,1

In [13]:
def quanQual(dataset):
    quan=[]
    qual=[]
    for columnName in dataset.columns:
        #print(columnName)
        if(dataset[columnName].dtype=='O'):
            #print("qual")
            qual.append(columnName)
        else:
            #print("quan")
            quan.append(columnName)
    return quan,qual

In [14]:
quan,qaul=quanQual(dataset)

In [15]:
dataset[quan]

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,depression_label,gender_male,platform_usage_Instagram,platform_usage_TikTok,social_interaction_level_low,social_interaction_level_medium
0,14,7.9,7.4,2.9,3.01,1.5,2,2,1,0,1,1,0,1,0
1,19,1.9,8.0,2.9,3.22,0.8,8,1,10,0,0,0,1,0,0
2,17,1.3,7.6,0.5,3.92,0.0,2,4,2,0,0,1,0,0,0
3,15,7.4,6.9,1.6,3.48,0.8,1,7,9,0,1,0,1,0,1
4,15,4.7,4.9,3.0,2.37,1.4,3,5,2,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,18,6.8,6.6,2.0,2.76,1.0,3,4,4,0,0,1,0,1,0
1196,16,2.3,8.0,1.9,2.12,0.4,7,4,4,0,1,0,0,0,0
1197,14,1.7,8.7,0.7,3.98,0.8,1,1,1,0,0,0,0,0,0
1198,15,3.9,8.5,2.1,3.19,0.6,7,9,9,0,1,0,0,0,0
1199,16,4.7,6.5,1.0,2.91,0.9,5,7,3,0,0,0,1,0,1

In [16]:
import numpy as np
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
imp.fit(dataset[quan])
df=imp.transform(dataset[quan])
df = pd.DataFrame(df,columns = quan)

In [17]:
df

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,depression_label,gender_male,platform_usage_Instagram,platform_usage_TikTok,social_interaction_level_low,social_interaction_level_medium
0,14.0,7.9,7.4,2.9,3.01,1.5,2.0,2.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0
1,19.0,1.9,8.0,2.9,3.22,0.8,8.0,1.0,10.0,0.0,0.0,0.0,1.0,0.0,0.0
2,17.0,1.3,7.6,0.5,3.92,0.0,2.0,4.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0
3,15.0,7.4,6.9,1.6,3.48,0.8,1.0,7.0,9.0,0.0,1.0,0.0,1.0,0.0,1.0
4,15.0,4.7,4.9,3.0,2.37,1.4,3.0,5.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,18.0,6.8,6.6,2.0,2.76,1.0,3.0,4.0,4.0,0.0,0.0,1.0,0.0,1.0,0.0
1196,16.0,2.3,8.0,1.9,2.12,0.4,7.0,4.0,4.0,0.0,1.0,0.0,0.0,0.0,0.0
1197,14.0,1.7,8.7,0.7,3.98,0.8,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1198,15.0,3.9,8.5,2.1,3.19,0.6,7.0,9.0,9.0,0.0,1.0,0.0,0.0,0.0,0.0
1199,16.0,4.7,6.5,1.0,2.91,0.9,5.0,7.0,3.0,0.0,0.0,0.0,1.0,0.0,1.0

In [20]:
cate=dataset[qaul]

In [21]:
cate

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[1200 rows x 0 columns]

In [22]:
two=[df,cate]

In [23]:
preprocessed=pd.concat(two,axis=1)

In [24]:
preprocessed

,age,daily_social_media_hours,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,stress_level,anxiety_level,addiction_level,depression_label,gender_male,platform_usage_Instagram,platform_usage_TikTok,social_interaction_level_low,social_interaction_level_medium
0,14.0,7.9,7.4,2.9,3.01,1.5,2.0,2.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0
1,19.0,1.9,8.0,2.9,3.22,0.8,8.0,1.0,10.0,0.0,0.0,0.0,1.0,0.0,0.0
2,17.0,1.3,7.6,0.5,3.92,0.0,2.0,4.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0
3,15.0,7.4,6.9,1.6,3.48,0.8,1.0,7.0,9.0,0.0,1.0,0.0,1.0,0.0,1.0
4,15.0,4.7,4.9,3.0,2.37,1.4,3.0,5.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,18.0,6.8,6.6,2.0,2.76,1.0,3.0,4.0,4.0,0.0,0.0,1.0,0.0,1.0,0.0
1196,16.0,2.3,8.0,1.9,2.12,0.4,7.0,4.0,4.0,0.0,1.0,0.0,0.0,0.0,0.0
1197,14.0,1.7,8.7,0.7,3.98,0.8,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1198,15.0,3.9,8.5,2.1,3.19,0.6,7.0,9.0,9.0,0.0,1.0,0.0,0.0,0.0,0.0
1199,16.0,4.7,6.5,1.0,2.91,0.9,5.0,7.0,3.0,0.0,0.0,0.0,1.0,0.0,1.0

In [25]:
preprocessed.to_csv("social_interaction_level_medium.csv",index=False)